### ISSUE TITLE
Is there a guide to e-commerce features?

### ISSUE THREAD

**Issue by JCorners68** [aws-samples/aws-amplify-ecommerce#4]
I was able to get through this demo but I cannot see any of the normal e-commerce functions such as 

- managing inventory pricing
- payments
- customers

help would be appreciated.

**Comment by StefanBuchman** [comment]
@JCorners68 

The sample is not a full e-commerce store but rather a demonstration of AWS Amplify and Amazon Pinpoint through the use of an e-commerce experience.
