### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by aaronbarnaby** [aws-samples/aws-amplify-ecommerce#5]
After running all the steps (only difference is I used Visual Studio Code instead of Cloud9)

When running the PROD settings S3 with Cloudfront HTTPS I'm getting Access Denied when trying to access the endpoint url.

Is there an issue with this sample that hasn't been updated?
Or have i missed something?

this is AFTER running `amplify publish`

**Comment by StefanBuchman** [comment]
@aaronbarnaby 

Just deployed the sample code and with CloudFront and S3 and didn't get an Access Denied.  I do need to fix the Amplify Authentication HoC but was able to register and see the store afterwards.

Did you wait enough time for the static site to upload to S3?  The deployment process can take up to 15 minutes.  Validate you see files in the hosting S3 bucket.

**Comment by aaronbarnaby** [comment]
Ye all the files was there.
I just ran it through again and on the DEV path  `DEV (S3 only with HTTP)`
it loads file (the styles don't work as per the example though it's all un-styled)

but when you use the PROD path it doesn't work and the link always gives Access Denied even though the files are there.   

Is there something else required for the production version ?

**Comment by StefanBuchman** [comment]
No, just ran through it again and works first time for me.

**Comment by aaronbarnaby** [comment]
![image](https://user-images.githubusercontent.com/30352676/83897423-7fff9c80-a74d-11ea-8ecb-a56a1cdc9ef2.png)

Nope I've done it again followed the step exactly and everything says it completed
![image](https://user-images.githubusercontent.com/30352676/83897589-afaea480-a74d-11ea-9158-e088ac8d1b97.png)

but when navigating to the url provided i get:
![image](https://user-images.githubusercontent.com/30352676/83897651-bfc68400-a74d-11ea-8d4a-dff6308a8326.png)
